### ISSUE TITLE
Example failed in Windows 7

### ISSUE THREAD

**Issue by hh9527** [nc4rrillo/indigo#60]
OS: Windows7-64
Rust: rustc 1.23.0-nightly (3b82e4c74 2017-11-05)
Toolchain: msvc

In my corporation's virtual desktop (Citrix based).

```
d:\dws\indigo\indigo (master)
λ cargo run --example todos
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `d:\dws\indigo\target\debug\examples\todos.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelForm
at', src\libcore\result.rs:906:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:92
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::result::unwrap_failed<glutin::CreationError>
             at C:\projects\rust\src\libcore\macros.rs:23
   9: core::result::Result<glutin::GlWindow, glutin::CreationError>::unwrap<glutin::GlWindow
,glutin::CreationError>
             at C:\projects\rust\src\libcore\result.rs:772
  10: indigo::ui::application::Application::new
             at .\src\ui\application.rs:58
  11: todos::main
             at .\examples\todos\main.rs:98
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:99
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  16: BaseThreadInitThunk
error: process didn't exit successfully: `d:\dws\indigo\target\debug\examples\todos.exe` (ex
it code: 101)
```

**Comment by nc4rrillo** [comment]
Hm, that's an error creating the OpenGL context, specifically setting the Pixel Format. I'm wondering if its related to the virtual desktop environment. 
Have you tried running Servo on this setup? I'd imagine you get a similar issue.

**Comment by hh9527** [comment]
Sorry, my personal laptop is a Macbook, so, for now, I have no non-virtual windows desktop to test.
I test the glutin project, same problem, so it should be a issue in glutin. https://github.com/tomaka/glutin/issues/952

**Comment by nc4rrillo** [comment]
I'm going to close this in favor of the bug you have open with glutin.
